### ISSUE TITLE
Resize from size 0 fails on OSX

### ISSUE THREAD

**Issue by jasminemoore-verses** [MathGeniusJodie/joann#3]
https://github.com/MathGeniusJodie/joann/blob/e0eae2c749456918ceb7b3a23a6d6daf37a02035/src/lib.rs#L110 attempts an mmap.flush() call, which calls through to `msync(PTR, 0, MS_SYNC)`. However, [https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/msync.2.html shows that this will result in OsErr 22, as 0 is not a valid ](https://stackoverflow.com/questions/60178688/uio-and-msync-why-does-msync-return-invalid-argument-even-though-the-address) shows that this is calling through to `fasync`, which must not have 0 as its length of file to sync. This will cause issues when resizing from 0 on OSX hosts.

**Comment by MathGeniusJodie** [comment]
fixed
